logingw:
  rest:
    # Rest General Config
    jwt:
      exp-time: 4
      alg-name: "RS256"
    config:
      some-key: "BETA"

    # Users (config-defined)
    users:
      known-users:
        -
          username: "user1"
          password: "password1"
          groups:
        -
          username: "TestUser"
          password: "password123"
          email: "test@abs.com"
          groups:
            - "groupA"
            - "groupB"

    # Rest Auth Config (AD)
    auth:
      ad:
        ldap:
          domain: "some.domain.com"
          url: "ldaps://some.domain.com:636/"
          search-filter: "(samaccountname={1})"

# App Config
spring:
  application:
    name: "login-gateway"
  jmx:
    enabled: true
server:
  port: 9090

# Health Check Config + JMX Config
springdoc:
  show-actuator: true

management:
  health:
    ldap:
      #TODO: Enable Ldap check for actuator/health when fully Implemented - issue #34
      enabled: "false"
  endpoints:
    jmx:
      exposure:
        include: "health"
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: "never"
