logingw:
  rest:
    jwt:
      exp-time: '4'
      alg-name: RS256
    config:
      some-key: BETA

    users:
      enabled: true
      known-users:
        -
          username: "user1"
          password: "password1"
          email: "user1@example.com"
          groups:
        -
          username: "TestUser"
          password: "password123"
          email: "test@abs.com"
          groups:
            - "groupA"
            - "groupB"

spring:
  application:
    name: login-gateway

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: '9090'
