logingw:
  rest:
    jwt:
      exp-time: 4
      alg-name: "RS256"
    config:
      some-key: "BETA"

    users:
      known-users:
        -
          username: "user1"
          password: "password1"
          groups:
        -
          username: "TestUser"
          password: "password123"
          email: "test@abs.com"
          groups:
            - "groupA"
            - "groupB"
    auth:
      ad:
        ldap:
          domain: "some.domain.com"
          url: "ldaps://some.domain.com:636/"
          search-filter: "(samaccountname={1})"

spring:
  application:
    name: "login-gateway"

server:
  port: 9090
