loginsvc:
  rest:
    # Rest General Config
    jwt:
      exp-time: 4
      alg-name: "RS256"
    config:
      some-key: "BETA"
      #Generates git.properties file for use on info endpoint.
      git-info:
        #Generate Git Information on each run of the application.
        generate-git-properties: true
        #Generate git.properties file on application startup.
        #Generate-git-properties must be true for this config to take effect.
        #Once file has been generated, you may set these properties to false as the application will now read the details from the generated file on start-up.
        generate-git-properties-file: false

    # Rest Auth Config (AD)
    auth:
      provider:
        # Users (config-defined)
        users:
          # Auth Protocol
          # Set the order of the protocol starting from 1
          # Set to 0 to disable or simply exclude the users tag from config
          # NOTE: At least 1 auth protocol needs to be enabled
          order: 1
          known-users:
            - username: "user1"
              password: "password1"
              groups: []
            - username: "TestUser"
              password: "password123"
              displayname: "Test User, A.C.E."
              email: "test@abs.com"
              groups:
                - "groupA"
                - "groupB"
        ldap:
          # Auth Protocol
          # Set the order of the protocol starting from 1
          # Set to 0 to disable or simply exclude the ldap tag from config
          # NOTE: At least 1 auth protocol needs to be enabled
          order: 2
          domain: "some.domain.com"
          url: "ldaps://some.domain.com:636/"
          search-filter: "(samaccountname={1})"

# App Config
spring:
  application:
    name: "login-service"
  jmx:
    enabled: true
server:
  port: 9090

# Health and Info Check Config + JMX Config
springdoc:
  show-actuator: true

management:
  health:
    ldap:
      #TODO: Enable Ldap check for actuator/health when fully Implemented - issue #34
      enabled: "false"
  # Expose information under Actuator/info
  info:
    # Exposes any property marked under "info" in the config
    env:
      enabled: "true"
    #Exposes git related information from the git.properties file
    git:
      enabled: "true"
    #Exposes Java runtime information
    java:
      enabled: "true"
    #Exposes build information
    build:
      enabled: "true"
  endpoints:
    jmx:
      exposure:
        include:
          - "health"
          - "info"
    web:
      exposure:
        include:
          - "health"
          - "info"
  endpoint:
    health:
      show-details: "never"

# Information to be exposed by the 'env' tag in the springboot actuator
info:
  app:
    name: "${spring.application.name}"
    build: "0.1"
    description: "Application used a reusable authentication tool"
    env: "Dev"
  security:
    ldap: "Enabled"
